/* eslint-disable quotes */
const products = [
  {
    name: 'black summer dress',
    description: 'red summer dress perfect for outdoors',
    category: ['dress', 'apparel'],
    price: 302.5,
    sizes: 'small',
    image: 'https://unsplash.com/photos/4mLKBKMPoHo',
    brand: 'ritzy',
    instock: true,
    rating: 5.0,
    colors: [
      { name: 'red', Hex: '#FF0000' },
      { name: 'grey', Hex: '#333' },
    ],
  },
  {
    name: 'out door dress',
    description: 'red summer dress, perfect for summer time',
    category: ['dress', 'apparel'],
    price: 250.3,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/m07caaQChc4',
    brand: 'outdoor life',
    instock: true,
    rating: 5.0,
    colors: [
      { name: 'gold', Hex: '#FF0000' },
      { name: 'grey', Hex: '#333' },
    ],
  },
  {
    name: 'satin dress',
    description: 'short open satin dress',
    category: ['dress', 'apparel'],
    price: 220.3,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/sTrDy5UU-XA',
    brand: 'outdoor life',
    instock: true,
    rating: 4.0,
    colors: [
      { name: 'pink', Hex: '#FF0000' },
      { name: 'blue', Hex: '#333' },
    ],
  },
  {
    name: 'sleeve dress',
    description: 'long sleeved dress',
    category: ['dress', 'apparel'],
    price: 220.3,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/kEC0A-dOw4g',
    brand: 'outdoor life',
    instock: true,
    rating: 4.0,
    colors: [
      { name: 'pink', Hex: '#FF0000' },
      { name: 'blue', Hex: '#333' },
    ],
  },
  {
    name: 'floral top dress',
    description: 'pink, black and white floral top dress',
    category: ['dress', 'apparel'],
    price: 280.99,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/0C2qrwkR1dI',
    brand: 'outdoor life',
    instock: true,
    rating: 4.0,
    colors: [
      { name: 'pink', Hex: '#FF0000' },
      { name: 'red', Hex: '#333' },
    ],
  },
  {
    name: 'spaghetti strap dress',
    description: 'spaghetti strap dress for cocktail events or other intimate events',
    category: ['dress', 'apparel'],
    price: 399.99,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/SQZl2ykH7E8',
    brand: 'Unsplash',
    instock: true,
    rating: 4.0,
    colors: [
      { name: 'pink', Hex: '#FF0000' },
      { name: 'red', Hex: '#333' },
    ],
  },
  {
    name: 'off shoulder top dress',
    description: 'off shoulder top dress with straps',
    category: ['dress', 'apparel'],
    price: 399.99,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/BOHyxqepP9Y',
    brand: 'Unsplash',
    instock: true,
    rating: 4.0,
    colors: [
      { name: 'pink', Hex: '#FF0000' },
      { name: 'red', Hex: '#333' },
    ],
  },
  {
    name: 'top dress',
    description: 'short top dress',
    category: ['dress', 'apparel'],
    price: 259.99,
    sizes: 'medium',
    image: 'https://unsplash.com/photos/tY3A3H8mAw8',
    brand: 'Unsplash',
    instock: true,
    rating: 4.0,
    colors: [
      { name: 'yellow', Hex: '#FF0000' },
      { name: 'red', Hex: '#333' },
    ],
  },
];
